- react_frontend/src/AppContainer.js
- react_frontend/src/Header.js
- react_frontend/src/Menu.js
- react_frontend/src/MenuList.js
- react_frontend/src/Navigation.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/Tab.js
- react_frontend/src/Tabbar.js
- react_frontend/src/assets/css/header.css
- react_frontend/src/assets/css/main.css
- react_frontend/src/assets/css/menu.css
- react_frontend/src/assets/css/navigation.css
Tab 기능 추가하였습니다. 
CSS 변경점 :
- 배경 색 gradient 추가
- 탭 CSS 추가
> [Feat] Tab 기능 구현 및 Css 수정 

- react_frontend/src/AppContainer.js
- react_frontend/src/Favorite.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/Tabbar.js
- react_frontend/src/assets/css/favorite.css
- react_frontend/src/components/Mal.js
우측에 즐겨찾기 기능 구현하였습니다.
즐겨찾기 누르면 접었다 폈다 할 수 있습니다.
아직 즐겨찾기 추가 방식을 정하지 못해 
- 즐겨찾기 메뉴 내용 구성하기
- 즐겨찾기 메뉴 클릭시 해당 탭 생성 및 이동
의 기능을 구현하지 못했습니다.
> [Feat] 즐겨찾기 기능 구현

- react_frontend/package-lock.json
- react_frontend/package.json
- react_frontend/public/index.html
- react_frontend/src/AppContainer.js
- react_frontend/src/Header.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/assets/css/app.css
- react_frontend/src/assets/css/layer.css
- react_frontend/src/assets/css/main.css
- react_frontend/src/assets/css/navbar.css
- react_frontend/src/assets/css/navigation.css
- react_frontend/src/assets/css/table.css
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mm.js
npm install @mui/material @emotion/react @emotion/styled
npm install @mui/material @mui/styled-engine-sc styled-components
npm install @fontsource/roboto
npm install @mui/icons-material
npm install antd 
하면 됨.
컴포넌트 세로로 늘어날 시 좌측 네비게이션 바 고정되게 구현
> [Feat] Mui & Antd 추가 및 네비게이션바 수정

- react_frontend/src/App.js
> [Fix] git conflict

- react_frontend/src/App.js
- react_frontend/src/Footer.js
- react_frontend/src/assets/css/footer.css
- react_frontend/src/assets/css/login.css
- react_frontend/src/components/login/Login.js
> [Fix] 이미지 깨짐 현상 수정

- react_frontend/public/index.html
- react_frontend/src/App.js
- react_frontend/src/AppContainer.js
- react_frontend/src/Header.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/assets/css/header.css
- react_frontend/src/assets/css/main.css
- react_frontend/src/assets/css/table.css
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/utils/Api.js
- react_frontend/src/utils/AxiosInstance.js
> [Fix] user 로그인 및 로그아웃 구현

- react_frontend/src/SearchForms.js
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/components/emperf/Ps_1_2.js
[Refactor] SearchForm 공통 컴포넌트화 구현
> [Refactor] SearchForm 공통 컴포넌트화 구현

- react_frontend/package-lock.json
- react_frontend/src/SearchForms.js
- react_frontend/src/Table.js
- react_frontend/src/TableCustom.js
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/assets/json/tep.js
- react_frontend/src/components/emperf/Ps_1_2.js
- react_frontend/src/components/emperf/perflook/Tep.js
- react_frontend/src/components/fieldinfo/project/Pd.js
- react_frontend/src/modals/Ps12Modal.js
* SearchForms.js에 props 추가 - autoSubmitOnInit=false
검색조건에 default값이 있어서 첫 렌더링 시 결과가 바로 뜨도록 하려면 autoSubmitOnInit=true 주시면 됩니다
* Table.js에 데이터가 비어 있을 경우 처리 추가
> [Feat] 총량실적 조회 화면 구현

- react_frontend/package-lock.json
- react_frontend/src/TableCustom.js
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/assets/json/selectedPjt.js
- react_frontend/src/components/fieldinfo/facility/Fad.js
- react_frontend/src/components/fieldinfo/facility/Fam.js
- react_frontend/src/components/fieldinfo/facility/Fl.js
- react_frontend/src/components/fieldinfo/project/Pd.js
- react_frontend/src/components/fieldinfo/project/Pg.js
- react_frontend/src/components/fieldinfo/project/Rm.js
- react_frontend/src/modals/PdModal.js
기본 화면 구성 (모달 기능 제외) 리스트입니다.
- 프로젝트 관리
- 매출액 관리
- 설비 LIB 관리
- 활동자료 관리
- 활동자료 지정
담당자 지정 기능은 PR 완료해서 제외했습니다.
> [Feat] 기본 화면 구현 (#64)

- react_frontend/src/Navigation.js
- react_frontend/src/assets/css/navigation.css
> [Feat] Navigation Fold 기능 구현

- react_frontend/src/Button.js
- react_frontend/src/Main.js
- react_frontend/src/Table.js
- react_frontend/src/assets/css/grid.css
- react_frontend/src/assets/css/pdModal.css
- react_frontend/src/assets/css/pjtModal.css
- react_frontend/src/assets/css/sysmng.css
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/assets/json/selectedPjt.js
- react_frontend/src/components/fieldinfo/Efm.js
- react_frontend/src/components/fieldinfo/facility/Fm.js
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
모든 컴포넌트에 (SearchForm 제외) Card를 적용했습니다.
관련된 css 는 sysmng.css 에서 확인할 수 있으며, Card에 sx={{borderRadious:"15[x"}} 적용 바랍니다.
그리고 테이블, 버튼, 모달 색상 중간발표 이전이기 때문에 우선 임시로 파랑계열로 색상 통일해놓았으며,
추후에 테마 색상 변경 시 위 컴포넌트 역시 변경 예정입니다. (말그대로 임시)
삭제 버튼 클릭시 나오는 모달은 일단 DeleteModal 로 하였으며 (Del Modal 디자인이 일단 잘 모르겠음..) 이것도 임시 모달이니 추후에 변경 예정입니다.
> [Feat] 시스템구현 & 배출계수 관리 & 설비 지정 css 수정 및 테이블, 버튼, 모달 색상 수정

- react_frontend/src/Menu.js
- react_frontend/src/MenuList.js
- react_frontend/src/Navigation.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/assets/css/menu.css
> 네비게이션 호버 및 현재 위치 표시 기능 생성

- react_frontend/src/Button.js
- react_frontend/src/FormItem/DropDown.js
- react_frontend/src/FormItem/SearchBtn.js
- react_frontend/src/InnerTabs.js
- react_frontend/src/assets/css/esm.css
- react_frontend/src/assets/css/formItem.css
- react_frontend/src/assets/css/innerTabs.css
- react_frontend/src/assets/css/ps12.css
- react_frontend/src/assets/css/ps12UploadExcelModal.css
- react_frontend/src/assets/css/searchForm.css
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/components/emperf/Ps_1_2.js
- react_frontend/src/components/emperf/perflook/Psq.js
- react_frontend/src/components/emperf/perflook/Tep.js
- react_frontend/src/components/fieldinfo/emission/Esm.js
- react_frontend/src/modals/PdModal.js
formItem 중 dropDown - 옵션의 길이와 맞도록 width 수정
searchForm - formItem 간 gap 설정
화면마다 <Card> 적용, css 수정 및 추가
> [Style] css 수정 및 추가

- react_frontend/package-lock.json
- react_frontend/package.json
- react_frontend/src/components/fieldinfo/project/Pd.js
- react_frontend/src/modals/PdModal.js
sweetAlert 기능 구현
- npm install sweetalert 해야함
> [Feat] 삭제 버튼 데이터 전달

- react_frontend/src/FormItem/SearchAtModal.js
- react_frontend/src/FormItem/SearchLibModal.js
- react_frontend/src/FormItem/SearchProjectModal.js
- react_frontend/src/TableCustom.js
- react_frontend/src/assets/css/pjtModal.css
- react_frontend/src/assets/json/selectedPjt.js
- react_frontend/src/components/fieldinfo/facility/Fad.js
- react_frontend/src/modals/PdModal.js
> [Feat] 활동자료 지정 화면 구현

- react_frontend/package-lock.json
- react_frontend/src/App.js
- react_frontend/src/Button.js
- react_frontend/src/FormItem/SearchAtModal.js
- react_frontend/src/FormItem/SearchProjectModal.js
- react_frontend/src/Table.js
- react_frontend/src/TableCustom.js
- react_frontend/src/components/fieldinfo/Efm.js
- react_frontend/src/components/fieldinfo/facility/Fm.js
- react_frontend/src/modals/PdModal.js
- react_frontend/src/utils/AxiosInstance.js
[Feat] 설비 지정 & 프로젝트 찾기 모달 백엔드 연동
> [Feat] 설비 지정 & 프로젝트 찾기 모달 백엔드 연동

- react_frontend/src/FormItem/DropDown.js
- react_frontend/src/Menu.js
- react_frontend/src/Navigation.js
- react_frontend/src/SiteLayout.js
- react_frontend/src/Table.js
- react_frontend/src/TableCustom.js
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/components/fieldinfo/Efm.js
- react_frontend/src/components/fieldinfo/facility/Fm.js
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mal.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
- react_frontend/src/utils/AxiosInstance.js
[Feat] 시스템관리 및 배출계수 지정 & 설비 지정 백엔드 연동 (메뉴관리 제외)
상세설명은 change file 에 적어놓겠습니다.
> [Feat] 시스템관리 및 배출계수 지정 & 설비 지정 백엔드 연동 (메뉴관리 제외)

- react_frontend/src/FormItem/SearchProjectModal.js
- react_frontend/src/assets/css/rmModal.css
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/components/fieldinfo/project/Pg.js
- react_frontend/src/modals/PdModal.js
> [Feat] 프로젝트 관리 api 연동

- react_frontend/src/SearchForms.js
- react_frontend/src/components/emperf/Ps_1_2.js
엑셀 관련 기능들은 나머지 페이지들 백엔드 연동 후에 할 예정입니다~!
> [Feat] 탭 별 데이터 분리, 프로젝트 선택시 대상년도 초기화

- react_frontend/src/App.js
- react_frontend/src/assets/css/sysmng.css
- react_frontend/src/components/fieldinfo/Efm.js
- react_frontend/src/components/fieldinfo/facility/Fm.js
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mal.js
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
[Feat] 메뉴 관리 수정 및 수정 시 반영 및 전체 Css 수정
> [Feat] 메뉴 관리 수정 및 수정 시 반영 및 전체 Css 수정

- react_frontend/package-lock.json
- react_frontend/package.json
- react_frontend/src/FormItem/SearchAtModal.js
- react_frontend/src/FormItem/SearchProjectModal.js
- react_frontend/src/Table.js
- react_frontend/src/TableCustom.js
- react_frontend/src/assets/json/tableColumn.js
- react_frontend/src/components/fieldinfo/Efm.js
- react_frontend/src/components/fieldinfo/facility/Fm.js
- react_frontend/src/components/fieldinfo/project/Pg.js
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mal.js
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
사용방법:
```<CustomTable />```태그에 
```<CustomTable columns={컬럼명} />```처럼 사용해주시면 됩니다.
위에 해당하는 컬럼명은 
```assets/json/tableColumn.js```에 Swagger에 나와있는 api 주소 처럼 이름을 작성하였으니 보고 참고하시면 됩니다.
ex)
```
<CustomTable columns={pjtColumns} />
아마처음 실행하게 되면 테이블의 컬럼명이 전부 지워져있을 텐데 위 작업 해줄 시 한글로 정상 실행됩니다. 
필요한 tableColumns을 추가로 작성 시 이름은 api주소+필요한이름 으로 해주세요.
```javascript
export const bbingDdangColumns = [
{ key: '', label: '', hidden: false } // key = 컬럼영문명, label = 원하는 한글 이름, hidden = true-> 숨기기, false -> 보이기
]
```
궁금한점 있으면 댓글달아주세여
> [Feat] 테이블 칼럼 hidden 및 한글화 처리 통합

- react_frontend/src/FormItem/DropDown.js
- react_frontend/src/FormItem/InputText.js
- react_frontend/src/FormItem/InputYear.js
- react_frontend/src/FormItem/SearchAtModal.js
- react_frontend/src/FormItem/SelectCalendar.js
- react_frontend/src/SearchForms.js
- react_frontend/src/assets/css/formItem.css
- react_frontend/src/assets/css/sdModal.css
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/assets/json/tableColumn.js
- react_frontend/src/components/emperf/Ps_1_2.js
- react_frontend/src/components/emperf/perflook/Psq.js
- react_frontend/src/components/emperf/perflook/Tep.js
- react_frontend/src/components/fieldinfo/emission/Esm.js
- react_frontend/src/modals/PdModal.js
안 된 기능들
활동량 관리 - 엑셀 업로드, 엑셀 양식 다운로드
총량실적조회, 프로젝트별조회 - 엑셀 다운로드
배출원 관리 - 증빙자료 등록, 증빙자료 상세보기
> [Feat] 총량실적조회, 프로젝트별조회, 배출원관리 백엔드 연동

- react_frontend/src/TableCustom.js
- react_frontend/src/assets/css/sdModal.css
- react_frontend/src/assets/json/sd.js
- react_frontend/src/assets/json/tableColumn.js
- react_frontend/src/components/emperf/Ps_1_2.js
- react_frontend/src/components/emperf/perflook/Psq.js
- react_frontend/src/components/emperf/perflook/Tep.js
- react_frontend/src/components/fieldinfo/emission/Esm.js
- react_frontend/src/modals/PdModal.js
총량실적조회, 프로젝트별조회 - 엑셀 다운로드
배출원 관리 - 증빙자료 등록, 증빙자료 상세보기&수정
> [Feat] 증빙자료 모달 관련 기능, 엑셀 다운로드 구현

- react_frontend/src/TabsContainer.js
> [HotFix] Tab Css 수정

- react_frontend/src/TableCustom.js
- react_frontend/src/TabsContainer.js
- react_frontend/src/assets/css/sysmng.css
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
> [Refactor] 시스템 관리 페이지 피드백 반영

- react_frontend/src/assets/css/pdModal.css
- react_frontend/src/assets/css/rmModal.css
- react_frontend/src/assets/css/sysmng.css
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
[Feat] 필수값 *표시
필수값표기
<span>*</span> 제목 -> *제목 이 되게
color: red;
font-size: 0.9rem;
부모 컴포넌트는
display:flex;
align-items: center;로 해주쇼(flex-direction이 column인경우는 justify-content-center)
> [Feat] 필수값 *표시

- react_frontend/src/Main_Admin.js
- react_frontend/src/Table.js
- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/assets/json/tableColumn.js
- react_frontend/src/components/sysmng/Cm.js
- react_frontend/src/components/sysmng/Mal.js
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
[Fix] 시스템 관리자 메뉴 및 메인보드 무한루프 제거
> [Fix] 시스템 관리자 메뉴 및 메인보드 무한루프 제거

- react_frontend/src/Main_Hp.js
- react_frontend/src/assets/css/gridHp.css
- react_frontend/src/components/fieldinfo/facility/Adm.js
- react_frontend/src/modals/PdModal.js
[Refactor] 본사담당자 메인보드 배출량 및 활동량으로 수정
> [Refactor] 본사담당자 메인보드 배출량 및 활동량으로 수정

- react_frontend/src/Chat.js
- react_frontend/src/chat/ChatList.js
- react_frontend/src/chat/Chatting.js
- react_frontend/src/chat/UserList.js
> [Feat] 공지사항 기능 구현

- react_frontend/src/chat/Chatting.js
[Feat] 공지사항 읽음 버튼 및 기능 구현
채팅 완성
> [Feat] 공지사항 읽음 버튼 및 기능 구현

- react_frontend/src/App.js
- react_frontend/src/Chat.js
- react_frontend/src/Main.js
- react_frontend/src/Main_Hp.js
- react_frontend/src/assets/css/gridHp.css
- react_frontend/src/chat/Chatting.js
- react_frontend/src/components/sysmng/Mm.js
- react_frontend/src/components/sysmng/Um.js
- react_frontend/src/modals/PdModal.js
> [Fix] 10/1 피드백 수정사항 반영

- react_frontend/src/Chat.js
- react_frontend/src/Main_Hp.js
- react_frontend/src/Table.js
- react_frontend/src/assets/css/chat.css
> [Style] 세부사항 수정

- react_frontend/src/Main_Hp.js
[Hotfix] 본사담당자 스코프 전월대비 퍼센트 계산식 수정
> [Hotfix] 본사담당자 스코프 전월대비 퍼센트 계산식 수정

- react_frontend/src/assets/json/searchFormData.js
- react_frontend/src/components/fieldinfo/facility/Adm.js
- react_frontend/src/components/fieldinfo/facility/Fl.js
> [Fix] 이전 PR 수정사항 반영
